version: '3.8'

x-app-vals: &app_vals
  build: .
  depends_on:
    - db

services:
  # Database stuff
  db:
    build: db
    container_name: db
    ports:
      - 27017:27017
  # Default app
  app:
    <<: *app_vals
    environment:
      MONGODB_URI: 'mongodb://db:27017/ml'
    command: 'start'
    ports:
      - 3000:3000
  # Jest test runner
  jest:
    <<: *app_vals
    environment:
      MONGODB_URI: 'mongodb://db:27017/test'
    command: 'test'
