name: 'Run database tests'

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker images
      run: |
        docker compose build

    - name: Run tests in Docker image
      run: |
        docker compose up jest
